### ISSUE TITLE
Grafana Example Not Working for mesos collector 

### ISSUE THREAD

**Issue by mohamedhaleem** [intelsdi-x/snap-plugin-collector-mesos#29]
Trying to visualize the data in grafana seems to be bringing up an empty page. I uploaded the JSON file from the examples directory. I confirmed that the stats are being pushed to our influxDB instance. (http://influxdb.x.x:8086/query?q=SHOW+MEASUREMENTS&db=influx

Could this be due to Grafana versions - we are using Grafana v3.1.1 (commit: a4d2708)  . I tried creating a dashboard, and it is showing data in the graphs.

Any pointers? Thanks

**Comment by rji** [comment]
It sounds like everything is configured correctly. The example dashboard assumes that you have a datasource configured in Grafana called "influx" that points at your InfluxDB database. Can you confirm that the datasource in Grafana matches your InfluxDB instance?

As for the Grafana version, the example dashboard should have been developed against either Grafana 3.0 or 3.1, so it should work (assuming the datasource is set up correctly).

**Comment by mohamedhaleem** [comment]
@rji thank you for looking into this. Somehow when i copy-pasted the json file, i messed up and did not notice a typo in the paste - it is now working as expected. 

thank you again and sorry about the trouble.

**Comment by rji** [comment]
No worries at all, glad to hear it's working for you now! Let me know if there's anything else I can help with 😊
